
sudo: required
dist: trusty

language: java
jdk:
  - openjdk8
  - oraclejdk8

env: GRADLE_OPTS="-Xms1g -Xmx3g"
install: true
script: ./gradlew build

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/521b6e832a3e037f9fa2
    on_success: change
    on_failure: always
    on_start: never
